message("-------------- factory start -------------")
file(GLOB_RECURSE FACTORY *.cpp)
add_library(factory SHARED ${FACTORY})
target_include_directories(factory PUBLIC ${CMAKE_SOURCE_DIR}/src)
target_include_directories(factory PUBLIC ${CMAKE_SOURCE_DIR}/tool)
target_include_directories(factory PUBLIC ${BOOST_INCLUDE_DIRS})
target_link_libraries(factory ${Boost_LIBS})
target_link_libraries(factory tool)
target_link_libraries(factory mat)
target_link_libraries(factory prop)
target_link_libraries(factory elem)
target_link_libraries(factory load)
target_link_libraries(factory coord)
target_link_libraries(factory constrain)
message("-------------- factory end   -------------")