cmake_minimum_required(VERSION 3.28)
project(FEASolver CXX)
set(CMAKE_CXX_STANDARD 11)
# # 添加子目录
find_package(Eigen3 REQUIRED)
if (Eigen3_FOUND)
    message(">>>Eigen3 FOUNED!!")
    set(Eigen3_INC_DIRS ${EIGEN3_INCLUDE_DIRS})
    
    find_package(Boost REQUIRED)
    if (Boost_FOUND)
        message(">>>Boost FOUND!!")
        # set(boost ${Boost})
        # 添加子目录
        add_subdirectory(src)
        add_subdirectory(tool)
        add_subdirectory(test)
    else()
        message(FATAL_ERROR "Boost NOT FOUND!")
    endif()
else()
    message(FATAL_ERROR "Eigen3 NOT FOUND!")
endif()

set(CMAKE_BUILD_TYPE Debug)
message("cmake_build_type: ${CMAKE_BUILD_TYPE}")