message("-------------- mapper start -------------")
file(GLOB_RECURSE MAPPER *.cpp)
add_library(mapper SHARED ${MAPPER})
target_include_directories(mapper PUBLIC ${CMAKE_SOURCE_DIR}/src)
target_include_directories(mapper PUBLIC ${BOOST_INCLUDE_DIRS})
target_link_libraries(mapper ${Boost_LIBS})
message("-------------- mapper end   -------------")