#pragma once
#include "register.h"
#include "component_factory/material_factory/factory_mat1.h"
#include "component_factory/property_factory/factory_prod.h"
#include "component_factory/property_factory/factory_pbar.h"
#include "component_factory/property_factory/factory_pshell.h"
#include "component_factory/property_factory/factory_psolid.h"
#include "component_factory/node_factory/factory_node.h"
#include "component_factory/element_factory/factory_D1/factory_rod.h"
#include "component_factory/element_factory/factory_D1/factory_cbar.h"
#include "component_factory/coordinate_factory/factory_cartesian_by_node.h"
#include "component_factory/load_factory/factory_concentrated_force.h"
#include "component_factory/load_factory/factory_uniformly_distribute_surf_load.h"
#include "component_factory/load_factory/factory_concentrated_moment.h"
#include "component_factory/constrain_factory/factory_single_point_constrain.h"
#include "component_factory/element_factory/factory_D2/factory_tria3.h"
#include "component_factory/element_factory/factory_D2/factory_cquad4_ml.h"
#include "component_factory/element_factory/factory_D3/factory_chexa8.h"


// 材料注册
MAPPER::Regist<FACTORY::Mat1Factory> _Mat1FactoryREGIST("MAT1");
// 节点注册
MAPPER::Regist<FACTORY::NodeFactory> _NodeFactoryREGIST("GRID");
// 属性注册
MAPPER::Regist<FACTORY::ProdFactory> _ProdFactoryREGIST("PROD");
MAPPER::Regist<FACTORY::PbarFactory> _PbarFactoryREGIST("PBAR");
MAPPER::Regist<FACTORY::PshellFactory> _PshellFactoryREGIST("PSHELL");
MAPPER::Regist<FACTORY::PsolidFactory> _PsolidFactoryREGIST("PSOLID");
// 单元注册 
MAPPER::Regist<FACTORY::RodFactory> _RodFactoryREGIST("CROD");
MAPPER::Regist<FACTORY::CBARFactory> _BarFactoryREGIST("CBAR");
MAPPER::Regist<FACTORY::TRIA3Factory> _Tria3FactoryREGIST("CTRIA3");
MAPPER::Regist<FACTORY::Cquad4MlFactory> _Cquad4KfFactoryREGIST("CQUAD4");
MAPPER::Regist<FACTORY::Chexa8Factory> _Chexa8FactoryREGIST("CHEXA8");
// 坐标系注册
MAPPER::Regist<FACTORY::CartesianByNodeFactory> _GlobalCoordFactoryREGIST("CORD1C");
// 载荷注册
MAPPER::Regist<FACTORY::ConcentratedForceFactory> _ConcentratedForceFactoryREGIST("FORCE");
MAPPER::Regist<FACTORY::ConcentratedMomentFactory> _ConcentratedMomentFactoryREGIST("MOMENT");
MAPPER::Regist<FACTORY::UnifDistributeSurfLoadFactory> _UnifDistributeSurfLoadFactory("USFORCE");
// 约束注册
MAPPER::Regist<FACTORY::SinglePointConstrainFactory> _SinglePointConstrainFactoryREGIST("SPC");