message("************** src start ***************")
add_subdirectory(component)
add_subdirectory(component_factory)
add_subdirectory(fea_model)
add_subdirectory(matrix_assemble)
add_subdirectory(model_mapper)
add_subdirectory(post_processor)
add_subdirectory(solver)
message("************** src end   ***************")
